// Enforces the architecture rules of CLAUDE.md §1 and §5 by scanning the
// source tree. The rule functions are pure (they take an in-memory
// [Project]), so the second half of this file proves each rule actually
// fails on a violation.
//
// Everything lives in this one file because only `architecture_test.dart`
// may sit at the test root, and tests import each other only by package URI.

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

// ---------------------------------------------------------------------------
// Model
// ---------------------------------------------------------------------------

const _package = 'expense_tracker';
const _layers = {'domain', 'data', 'presentation'};
const _apiKinds = {'routes', 'domain', 'data', 'presentation'};
const _layerFolders = {
  'domain': {'entities', 'repositories', 'usecases'},
  'data': {'models', 'datasources', 'repositories'},
  'presentation': {'pages', 'widgets', 'providers'},
};
const _appRootFiles = {'lib/main.dart', 'lib/app.dart'};
const _router = 'lib/core/router/app_router.dart';

class SourceFile {
  const SourceFile(this.path, this.content);

  /// Project-relative path with forward slashes, e.g. `lib/core/x.dart`.
  final String path;
  final String content;
}

class Project {
  Project(this.lib, this.test);

  /// Builds a project from `{path: content}`; paths starting with `lib/` or
  /// `test/` are sorted into the matching list.
  factory Project.of(Map<String, String> files) => Project(
    [
      for (final e in files.entries)
        if (e.key.startsWith('lib/')) SourceFile(e.key, e.value),
    ],
    [
      for (final e in files.entries)
        if (e.key.startsWith('test/')) SourceFile(e.key, e.value),
    ],
  );

  factory Project.fromDisk() {
    List<SourceFile> scan(String root) => [
      for (final entity in Directory(root).listSync(recursive: true))
        if (entity is File && entity.path.endsWith('.dart'))
          SourceFile(
            entity.path.replaceAll(r'\', '/'),
            entity.readAsStringSync(),
          ),
    ];
    return Project(scan('lib'), scan('test'));
  }

  final List<SourceFile> lib;
  final List<SourceFile> test;

  late final Set<String> libPaths = {for (final f in lib) f.path};

  /// Hand-written lib files (generated code is not held to the import rules).
  Iterable<SourceFile> get handWritten => lib.where((f) => !isGeneratedFile(f));
}

bool isGenerated(String path) =>
    path.endsWith('.g.dart') ||
    path.endsWith('.freezed.dart') ||
    path.startsWith('lib/core/l10n/generated/');

/// Generated by path, or by a tool header (e.g. drift_dev's migration test
/// helpers). Generated code is not held to the import rules.
bool isGeneratedFile(SourceFile file) =>
    isGenerated(file.path) ||
    RegExp(
      r'^// GENERATED (BY|CODE)',
      multiLine: true,
    ).hasMatch(file.content.substring(0, file.content.length.clamp(0, 400)));

/// Where a lib file sits in the architecture.
class Loc {
  const Loc.appRoot() : this._(Area.appRoot);
  const Loc.core() : this._(Area.core);
  const Loc.api(String module, String api)
    : this._(Area.feature, module: module, api: api);
  const Loc._(this.area, {this.module, this.api})
    : slice = null,
      layer = null,
      inner = const [],
      singleSlice = false;
  const Loc.layer(
    String this.module,
    String this.slice,
    String this.layer,
    this.inner, {
    required this.singleSlice,
  }) : area = Area.feature,
       api = null;

  final Area area;
  final String? module;
  final String? slice;
  final String? layer;

  /// For a module root file: `routes`, `domain`, `data` or `presentation`.
  final String? api;

  /// Path segments below the layer folder.
  final List<String> inner;
  final bool singleSlice;

  bool get isApi => api != null;
  bool get isShared => slice == 'shared' && !singleSlice;

  /// The layer whose import rules apply. Routes files compose pages, so they
  /// follow presentation rules.
  String? get effectiveLayer => api == 'routes' ? 'presentation' : layer;

  /// `data/<slice>_providers.dart`, the only data file presentation may use.
  bool get isWiring =>
      layer == 'data' &&
      inner.length == 1 &&
      inner.single == '${slice}_providers.dart';
}

enum Area { appRoot, core, feature }

/// Classifies [path] (under `lib/`); returns a [Loc] or throws a
/// [FormatException] explaining why the file is misplaced.
Loc classify(String path) {
  if (_appRootFiles.contains(path)) return const Loc.appRoot();
  final seg = path.split('/');
  if (seg.length > 2 && seg[1] == 'core') return const Loc.core();
  if (seg.length < 4 || seg[1] != 'features') {
    throw const FormatException(
      'must be under lib/core/ or lib/features/<module>/',
    );
  }
  final module = seg[2];
  final rest = seg.sublist(3);
  if (rest.length == 1) {
    final base = _stripGenerated(rest.single);
    for (final kind in _apiKinds) {
      if (base == '${module}_$kind.dart') return Loc.api(module, kind);
    }
    throw FormatException(
      'only ${module}_{routes,domain,data,presentation}.dart may sit at the module root',
    );
  }
  final singleSlice = _layers.contains(rest[0]);
  final slice = singleSlice ? module : rest[0];
  final layerIndex = singleSlice ? 0 : 1;
  if (rest.length < layerIndex + 2 || !_layers.contains(rest[layerIndex])) {
    throw const FormatException(
      'a slice folder must contain only domain/, data/ and presentation/',
    );
  }
  final layer = rest[layerIndex];
  final inner = rest.sublist(layerIndex + 1);
  final loc = Loc.layer(module, slice, layer, inner, singleSlice: singleSlice);
  if (inner.length == 1) {
    if (layer == 'data' &&
        _stripGenerated(inner.single) == '${slice}_providers.dart') {
      return loc;
    }
    throw FormatException(
      layer == 'data'
          ? 'only ${slice}_providers.dart may sit directly in data/'
          : 'files in $layer/ go in ${_layerFolders[layer]!.join('/, ')}/',
    );
  }
  if (!_layerFolders[layer]!.contains(inner.first)) {
    throw FormatException(
      '$layer/ may only contain ${_layerFolders[layer]!.join('/, ')}/',
    );
  }
  return loc;
}

String _stripGenerated(String name) =>
    name.replaceFirst(RegExp(r'\.(g|freezed)\.dart$'), '.dart');

class Directive {
  const Directive(this.keyword, this.uri);

  final String keyword;
  final String uri;

  bool get isRelative =>
      !uri.startsWith('dart:') && !uri.startsWith('package:');

  /// The lib path of a project import, or null for anything else.
  String? get target => uri.startsWith('package:$_package/')
      ? 'lib/${uri.substring('package:$_package/'.length)}'
      : null;

  @override
  String toString() => "$keyword '$uri'";
}

final _directivePattern = RegExp(
  r'''^\s*(import|export)\s+['"]([^'"]+)['"]''',
  multiLine: true,
);

List<Directive> directivesOf(String content) => [
  for (final m in _directivePattern.allMatches(content))
    Directive(m.group(1)!, m.group(2)!),
];

Loc? _tryClassify(String path) {
  try {
    return classify(path);
  } on FormatException {
    return null;
  }
}

// ---------------------------------------------------------------------------
// Rules. Each returns human-readable violations; empty means compliant.
// ---------------------------------------------------------------------------

typedef Rule = List<String> Function(Project project);

/// Every lib file is in an allowed place; modules are either single-slice or
/// sliced, never both; every module has its four root files.
List<String> placementRule(Project p) {
  final out = <String>[];
  final singleSliced = <String>{};
  final sliced = <String>{};
  final modules = <String>{};
  for (final file in p.lib) {
    try {
      final loc = classify(file.path);
      if (loc.module == null) continue;
      modules.add(loc.module!);
      if (loc.isApi) continue;
      (loc.singleSlice ? singleSliced : sliced).add(loc.module!);
    } on FormatException catch (e) {
      out.add('${file.path}: ${e.message}');
    }
  }
  for (final m in singleSliced.intersection(sliced)) {
    out.add(
      'lib/features/$m: has layers at the module root and slices; pick one',
    );
  }
  for (final m in modules) {
    for (final kind in _apiKinds) {
      final path = 'lib/features/$m/${m}_$kind.dart';
      if (!p.libPaths.contains(path)) {
        out.add('$path: missing module root file');
      }
    }
  }
  return out;
}

/// Layer rules inside a module (CLAUDE §1.1), core and app-root rules.
List<String> layerRule(Project p) {
  const bannedInDomain = [
    'package:flutter/',
    'package:flutter_riverpod/',
    'package:hooks_riverpod/',
    'package:riverpod',
    'package:drift',
    'dart:ui',
  ];
  final out = <String>[];
  for (final file in p.handWritten) {
    final from = _tryClassify(file.path);
    if (from == null) continue;
    for (final d in directivesOf(file.content)) {
      String fail(String why) => '${file.path}: $d — $why';

      if (from.effectiveLayer == 'domain' &&
          bannedInDomain.any(d.uri.startsWith)) {
        out.add(fail('domain must stay pure Dart'));
      }
      final target = d.target;
      if (target == null) continue;
      final to = _tryClassify(target);
      if (to == null) continue;

      if (to.area == Area.appRoot && file.path != 'lib/main.dart') {
        out.add(fail('only main.dart imports app.dart'));
        continue;
      }
      switch (from.area) {
        case Area.core:
          final routerComposesRoutes =
              file.path == _router && to.api == 'routes';
          if (to.area == Area.feature && !routerComposesRoutes) {
            out.add(
              fail(
                'core imports no feature (only the router composes <m>_routes.dart)',
              ),
            );
          }
        case Area.appRoot:
          if (to.area == Area.feature && to.api != 'presentation') {
            out.add(fail('app root may only use <m>_presentation.dart'));
          }
        case Area.feature:
          if (to.area != Area.feature || to.module != from.module) continue;
          if (from.isApi && from.api != 'routes') continue; // publicApiRule
          if (to.isApi) {
            out.add(
              fail(
                'inside a module, import files directly, not the public API',
              ),
            );
            continue;
          }
          final allowed = switch (from.effectiveLayer) {
            'domain' => to.layer == 'domain',
            'data' => to.layer == 'domain' || to.layer == 'data',
            _ =>
              to.layer == 'domain' || to.layer == 'presentation' || to.isWiring,
          };
          if (!allowed) {
            out.add(
              fail(
                '${from.effectiveLayer} may not import ${to.layer}'
                '${from.effectiveLayer == 'presentation' ? ' (only <slice>_providers.dart from data/)' : ''}',
              ),
            );
          }
      }
    }
  }
  return out;
}

/// Modules talk to each other only through the root API file matching the
/// importer's layer; `shared/` is private to its module.
List<String> crossModuleRule(Project p) {
  final out = <String>[];
  for (final file in p.handWritten) {
    final from = _tryClassify(file.path);
    if (from == null || from.area != Area.feature) continue;
    if (from.isApi && from.api != 'routes') continue;
    for (final d in directivesOf(file.content)) {
      final target = d.target;
      if (target == null) continue;
      final to = _tryClassify(target);
      if (to == null || to.area != Area.feature || to.module == from.module) {
        continue;
      }
      final want = from.effectiveLayer!;
      if (to.api != want) {
        out.add(
          '${file.path}: $d — cross-module imports go through '
          '${to.module}_$want.dart${to.isShared ? ' (shared/ is private to its module)' : ''}',
        );
      }
    }
  }
  return out;
}

/// `<m>_{domain,data,presentation}.dart` hold only `export … show …` of their
/// own module, from layers the matching importer could use directly.
List<String> publicApiRule(Project p) {
  final out = <String>[];
  final exportPattern = RegExp(
    r'''^export\s+'([^']+)'\s+show\s+[A-Za-z_$][\w$]*(\s*,\s*[A-Za-z_$][\w$]*)*$''',
  );
  for (final file in p.handWritten) {
    final loc = _tryClassify(file.path);
    if (loc == null || !loc.isApi || loc.api == 'routes') continue;
    final code = file.content
        .replaceAll(RegExp(r'//.*'), '')
        .replaceAll(RegExp(r'/\*[\s\S]*?\*/'), '');
    for (final raw in code.split(';')) {
      final statement = raw.trim().replaceAll(RegExp(r'\s+'), ' ');
      if (statement.isEmpty) continue;
      final match = exportPattern.firstMatch(statement);
      if (match == null) {
        out.add(
          '${file.path}: "$statement" — public API files contain only export … show … lines',
        );
        continue;
      }
      final target = Directive('export', match.group(1)!).target;
      final to = target == null ? null : _tryClassify(target);
      if (to == null || to.module != loc.module || to.isApi) {
        out.add(
          '${file.path}: "$statement" — may only export files of its own module',
        );
        continue;
      }
      final allowed = switch (loc.api) {
        'domain' => to.layer == 'domain',
        'data' => to.layer == 'domain' || to.layer == 'data',
        _ => to.layer == 'domain' || to.layer == 'presentation' || to.isWiring,
      };
      if (!allowed) {
        out.add(
          '${file.path}: "$statement" — ${loc.api} API may not expose ${to.layer}',
        );
      }
    }
  }
  return out;
}

/// Slices within a module and modules among themselves form acyclic graphs;
/// `shared/` imports no sibling slice.
List<String> graphRule(Project p) {
  final out = <String>[];
  final sliceEdges = <String, Set<String>>{};
  final moduleEdges = <String, Set<String>>{};
  for (final file in p.handWritten) {
    final from = _tryClassify(file.path);
    if (from == null || from.area != Area.feature) continue;
    for (final d in directivesOf(file.content)) {
      final target = d.target;
      if (target == null) continue;
      final to = _tryClassify(target);
      if (to == null || to.area != Area.feature) continue;
      if (to.module != from.module) {
        moduleEdges.putIfAbsent(from.module!, () => {}).add(to.module!);
        continue;
      }
      if (from.isApi || to.isApi || from.slice == to.slice) continue;
      if (from.isShared) {
        out.add(
          '${file.path}: $d — shared/ may not import sibling slice ${to.slice}',
        );
      }
      sliceEdges
          .putIfAbsent('${from.module}/${from.slice}', () => {})
          .add('${to.module}/${to.slice}');
    }
  }
  for (final cycle in [..._cycles(sliceEdges), ..._cycles(moduleEdges)]) {
    out.add('import cycle: ${cycle.join(' → ')}');
  }
  return out;
}

/// One representative cycle per strongly-connected back edge.
List<List<String>> _cycles(Map<String, Set<String>> edges) {
  final cycles = <List<String>>[];
  final state = <String, int>{}; // 1 = on stack, 2 = done
  final stack = <String>[];
  void visit(String node) {
    state[node] = 1;
    stack.add(node);
    for (final next in edges[node] ?? const <String>{}) {
      if (state[next] == 1) {
        cycles.add([...stack.sublist(stack.indexOf(next)), next]);
      } else if (state[next] == null) {
        visit(next);
      }
    }
    stack.removeLast();
    state[node] = 2;
  }

  for (final node in edges.keys.toList()..sort()) {
    if (state[node] == null) visit(node);
  }
  return cycles;
}

/// Every import in lib/ and test/ is a `package:` or `dart:` URI.
List<String> packageImportsRule(Project p) {
  // A test can reach a tool-generated helper beside it (drift's migration
  // schemas) only by a relative URI: package: URIs resolve into lib/.
  final generatedTests = {
    for (final f in p.test)
      if (isGeneratedFile(f)) f.path,
  };
  bool isGeneratedSibling(SourceFile from, Directive d) {
    if (!from.path.startsWith('test/')) return false;
    final dir = from.path.substring(0, from.path.lastIndexOf('/'));
    return generatedTests.contains('$dir/${d.uri}');
  }

  return [
    for (final file in [
      ...p.handWritten,
      ...p.test.where((f) => !isGeneratedFile(f)),
    ])
      for (final d in directivesOf(file.content))
        if (d.isRelative && !isGeneratedSibling(file, d))
          '${file.path}: $d — use package:$_package/…',
  ];
}

/// test/ mirrors lib/: only architecture_test.dart at the root, and every
/// other test file's folder exists under lib/.
List<String> testMirrorRule(Project p) {
  final libDirs = {
    for (final path in p.libPaths)
      for (var i = path.indexOf('/'); i != -1; i = path.indexOf('/', i + 1))
        path.substring(0, i),
  };
  final out = <String>[];
  for (final file in p.test) {
    if (file.path == 'test/architecture_test.dart') continue;
    final dir = file.path.substring(0, file.path.lastIndexOf('/'));
    if (dir == 'test') {
      out.add(
        '${file.path}: only architecture_test.dart sits at the test root',
      );
    } else if (!libDirs.contains('lib${dir.substring('test'.length)}')) {
      out.add(
        '${file.path}: lib${dir.substring('test'.length)}/ does not exist',
      );
    }
  }
  return out;
}

/// No `Map<String, dynamic>` in domain files (CLAUDE §1.2).
List<String> typedDomainRule(Project p) => [
  for (final file in p.handWritten)
    if (_tryClassify(file.path)?.layer == 'domain' &&
        RegExp(r'Map<\s*String\s*,\s*dynamic\s*>').hasMatch(file.content))
      '${file.path}: Map<String, dynamic> may not cross the domain boundary',
];

/// Riverpod is the only DI and state tool (CLAUDE §2).
List<String> stateManagementRule(Project p) {
  final banned = RegExp(
    r'\b(StateNotifier|StateNotifierProvider|StateProvider|ChangeNotifierProvider|GetIt)\b|package:get_it/',
  );
  return [
    for (final file in p.handWritten)
      if (banned.firstMatch(file.content) case final m?)
        '${file.path}: ${m.group(0)} — use Notifier/AsyncNotifier and Riverpod DI',
  ];
}

const Map<String, Rule> rules = {
  'placement': placementRule,
  'layers': layerRule,
  'cross-module': crossModuleRule,
  'public API files': publicApiRule,
  'import graph': graphRule,
  'package imports': packageImportsRule,
  'test mirror': testMirrorRule,
  'typed domain': typedDomainRule,
  'state management': stateManagementRule,
};

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

void main() {
  group('architecture of this project', () {
    final project = Project.fromDisk();
    for (final MapEntry(key: name, value: rule) in rules.entries) {
      test(name, () {
        final violations = rule(project);
        expect(violations, isEmpty, reason: violations.join('\n'));
      });
    }
  });

  group('rules catch violations', () {
    const pkg = 'package:$_package';

    /// A small compliant tree: single-slice module `categories`, sliced
    /// module `reports` with a `shared` slice, and a module `home` that uses
    /// both through their public APIs.
    Map<String, String> validTree() => {
      'lib/main.dart': "import '$pkg/app.dart';",
      'lib/app.dart':
          "import '$pkg/core/router/app_router.dart';\n"
          "import '$pkg/features/categories/categories_presentation.dart';",
      'lib/core/router/app_router.dart':
          "import '$pkg/features/home/home_routes.dart';",
      'lib/core/error/failure.dart': '',
      for (final m in ['categories', 'reports', 'home'])
        for (final kind in _apiKinds) 'lib/features/$m/${m}_$kind.dart': '',
      'lib/features/categories/categories_domain.dart':
          "export '$pkg/features/categories/domain/entities/category.dart' show Category;",
      'lib/features/categories/categories_presentation.dart':
          "export '$pkg/features/categories/domain/entities/category.dart' show Category;\n"
          "export '$pkg/features/categories/presentation/widgets/category_grid.dart'\n"
          '    show CategoryGrid, CategoryCell;',
      'lib/features/categories/domain/entities/category.dart':
          "import '$pkg/core/error/failure.dart';",
      'lib/features/categories/data/categories_providers.dart':
          "import '$pkg/features/categories/data/repositories/category_repository_impl.dart';",
      'lib/features/categories/data/repositories/category_repository_impl.dart':
          "import '$pkg/features/categories/domain/entities/category.dart';",
      'lib/features/categories/presentation/widgets/category_grid.dart':
          "import 'package:flutter/material.dart';\n"
          "import '$pkg/features/categories/data/categories_providers.dart';\n"
          "import '$pkg/features/categories/domain/entities/category.dart';",
      'lib/features/reports/shared/domain/entities/report_scope.dart': '',
      'lib/features/reports/statistics/domain/usecases/get_stats.dart':
          "import '$pkg/features/reports/shared/domain/entities/report_scope.dart';\n"
          "import '$pkg/features/categories/categories_domain.dart';",
      'lib/features/reports/statistics/presentation/pages/stats_page.dart':
          "import '$pkg/features/reports/statistics/domain/usecases/get_stats.dart';",
      'lib/features/reports/reports_presentation.dart':
          "export '$pkg/features/reports/statistics/presentation/pages/stats_page.dart' show StatsPage;",
      'lib/features/home/home_routes.dart':
          "import '$pkg/features/home/presentation/pages/home_page.dart';",
      'lib/features/home/presentation/pages/home_page.dart':
          "import '$pkg/features/reports/reports_presentation.dart';\n"
          "import '$pkg/features/categories/categories_presentation.dart';",
      'test/architecture_test.dart': '',
      'test/features/reports/statistics/domain/usecases/get_stats_test.dart':
          "import '$pkg/features/reports/statistics/domain/usecases/get_stats.dart';",
    };

    List<String> run(Map<String, String> changes, {Map<String, String>? base}) {
      final tree = {...(base ?? validTree()), ...changes};
      return [for (final rule in rules.values) ...rule(Project.of(tree))];
    }

    void expectViolation(Map<String, String> changes, String fragment) {
      final violations = run(changes);
      expect(
        violations.any((v) => v.contains(fragment)),
        isTrue,
        reason:
            'expected a violation containing "$fragment", got:\n${violations.join('\n')}',
      );
    }

    test('the valid tree passes every rule', () {
      expect(run(const {}), isEmpty);
    });

    group('placement', () {
      test('file outside core/features', () {
        expectViolation({'lib/utils/x.dart': ''}, 'lib/utils/x.dart');
      });
      test('unknown root file in a module', () {
        expectViolation({'lib/features/home/helpers.dart': ''}, 'module root');
      });
      test('unknown layer subfolder', () {
        expectViolation({
          'lib/features/home/domain/services/x.dart': '',
        }, 'domain/ may only contain');
      });
      test('loose file in presentation/', () {
        expectViolation({
          'lib/features/home/presentation/x.dart': '',
        }, 'files in presentation/');
      });
      test('extra file directly in data/', () {
        expectViolation({
          'lib/features/home/data/helpers.dart': '',
        }, 'only home_providers.dart');
      });
      test('slice without a layer folder', () {
        expectViolation({
          'lib/features/reports/daily/x.dart': '',
        }, 'slice folder');
      });
      test('module mixing layers and slices', () {
        expectViolation({
          'lib/features/home/greeting/domain/entities/g.dart': '',
        }, 'pick one');
      });
      test('module missing a root file', () {
        expectViolation({
          'lib/features/budget/domain/entities/b.dart': '',
        }, 'budget_routes.dart: missing');
      });
      test('generated files follow their source', () {
        expect(
          run({
            'lib/features/home/data/home_providers.g.dart': '',
            'lib/features/home/domain/entities/x.freezed.dart': '',
          }),
          isEmpty,
        );
      });
    });

    group('layers', () {
      test('domain importing Flutter', () {
        expectViolation({
          'lib/features/reports/shared/domain/entities/report_scope.dart':
              "import 'package:flutter/foundation.dart';",
        }, 'pure Dart');
      });
      test('domain importing Riverpod', () {
        expectViolation({
          'lib/features/reports/shared/domain/entities/report_scope.dart':
              "import 'package:riverpod_annotation/riverpod_annotation.dart';",
        }, 'pure Dart');
      });
      test('domain importing data', () {
        expectViolation({
          'lib/features/categories/domain/entities/category.dart':
              "import '$pkg/features/categories/data/categories_providers.dart';",
        }, 'domain may not import data');
      });
      test('data importing presentation', () {
        expectViolation({
          'lib/features/categories/data/categories_providers.dart':
              "import '$pkg/features/categories/presentation/widgets/category_grid.dart';",
        }, 'data may not import presentation');
      });
      test('presentation importing a repository impl', () {
        expectViolation({
          'lib/features/categories/presentation/widgets/category_grid.dart':
              "import '$pkg/features/categories/data/repositories/category_repository_impl.dart';",
        }, 'only <slice>_providers.dart');
      });
      test('core importing a feature', () {
        expectViolation({
          'lib/core/error/failure.dart':
              "import '$pkg/features/categories/categories_domain.dart';",
        }, 'core imports no feature');
      });
      test('router importing something other than routes', () {
        expectViolation({
          _router: "import '$pkg/features/home/home_presentation.dart';",
        }, 'core imports no feature');
      });
      test('a module importing its own public API', () {
        expectViolation({
          'lib/features/categories/presentation/widgets/category_grid.dart':
              "import '$pkg/features/categories/categories_presentation.dart';",
        }, 'not the public API');
      });
      test('importing app.dart', () {
        expectViolation({
          'lib/core/error/failure.dart': "import '$pkg/app.dart';",
        }, 'only main.dart imports app.dart');
      });
    });

    group('cross-module', () {
      test('reaching into another module slice', () {
        expectViolation({
          'lib/features/home/presentation/pages/home_page.dart':
              "import '$pkg/features/categories/presentation/widgets/category_grid.dart';",
        }, 'through categories_presentation.dart');
      });
      test('importing the API file of another layer', () {
        expectViolation({
          'lib/features/home/presentation/pages/home_page.dart':
              "import '$pkg/features/categories/categories_domain.dart';",
        }, 'through categories_presentation.dart');
      });
      test('importing another module shared/', () {
        expectViolation({
          'lib/features/home/presentation/pages/home_page.dart':
              "import '$pkg/features/reports/shared/domain/entities/report_scope.dart';",
        }, 'shared/ is private');
      });
      test('importing another module routes', () {
        expectViolation({
          'lib/features/home/presentation/pages/home_page.dart':
              "import '$pkg/features/categories/categories_routes.dart';",
        }, 'through categories_presentation.dart');
      });
    });

    group('public API files', () {
      test('code in an API file', () {
        expectViolation({
          'lib/features/home/home_domain.dart': 'const x = 1;',
        }, 'only export … show …');
      });
      test('export without show', () {
        expectViolation({
          'lib/features/categories/categories_domain.dart':
              "export '$pkg/features/categories/domain/entities/category.dart';",
        }, 'only export … show …');
      });
      test('exporting another module', () {
        expectViolation({
          'lib/features/home/home_domain.dart':
              "export '$pkg/features/categories/domain/entities/category.dart' show Category;",
        }, 'its own module');
      });
      test('domain API exposing data', () {
        expectViolation({
          'lib/features/categories/categories_domain.dart':
              "export '$pkg/features/categories/data/categories_providers.dart' show x;",
        }, 'domain API may not expose data');
      });
      test('presentation API exposing a repository impl', () {
        expectViolation({
          'lib/features/categories/categories_presentation.dart':
              "export '$pkg/features/categories/data/repositories/category_repository_impl.dart' show X;",
        }, 'presentation API may not expose data');
      });
    });

    group('import graph', () {
      test('slice cycle', () {
        expectViolation({
          'lib/features/reports/daily/domain/entities/day.dart':
              "import '$pkg/features/reports/statistics/domain/usecases/get_stats.dart';",
          'lib/features/reports/statistics/domain/usecases/get_stats.dart':
              "import '$pkg/features/reports/daily/domain/entities/day.dart';",
        }, 'import cycle');
      });
      test('module cycle', () {
        expectViolation({
          'lib/features/categories/presentation/widgets/category_grid.dart':
              "import '$pkg/features/home/home_presentation.dart';",
        }, 'import cycle: categories → home → categories');
      });
      test('shared importing a sibling slice', () {
        expectViolation({
          'lib/features/reports/shared/domain/entities/report_scope.dart':
              "import '$pkg/features/reports/statistics/domain/usecases/get_stats.dart';",
        }, 'shared/ may not import sibling slice statistics');
      });
    });

    test('relative import in lib', () {
      expectViolation({
        'lib/features/categories/domain/entities/category.dart':
            "import '../../../../core/error/failure.dart';",
      }, 'use package:$_package');
    });

    test('generated test helpers may use relative imports', () {
      expect(
        run({
          'test/features/reports/statistics/domain/usecases/schema.dart':
              '// dart format width=80\n// GENERATED BY drift_dev, DO NOT MODIFY.\n'
              "import 'schema_v1.dart' as v1;",
        }),
        isEmpty,
      );
    });

    test('a test may import a generated helper beside it', () {
      const dir = 'test/features/reports/statistics/domain/usecases';
      expect(
        run({
          '$dir/schema.dart': '// GENERATED BY drift_dev, DO NOT MODIFY.',
          '$dir/migration_test.dart': "import 'schema.dart';",
        }),
        isEmpty,
      );
      expectViolation({
        '$dir/helpers.dart': '// hand-written',
        '$dir/migration_test.dart': "import 'helpers.dart';",
      }, 'use package:');
    });

    test('relative import in test', () {
      expectViolation({
        'test/features/reports/statistics/domain/usecases/get_stats_test.dart':
            "import 'helpers.dart';",
      }, 'use package:$_package');
    });

    group('test mirror', () {
      test('test file at the root', () {
        expectViolation({'test/helpers_test.dart': ''}, 'test root');
      });
      test('test folder with no lib counterpart', () {
        expectViolation({
          'test/features/budget/budget_test.dart': '',
        }, 'lib/features/budget/ does not exist');
      });
    });

    test('Map<String, dynamic> in domain', () {
      expectViolation({
        'lib/features/categories/domain/entities/category.dart':
            'final Map<String, dynamic> json = {};',
      }, 'Map<String, dynamic>');
    });

    test('StateNotifier in lib', () {
      expectViolation({
        'lib/features/home/presentation/pages/home_page.dart':
            'class X extends StateNotifier<int> {}',
      }, 'StateNotifier');
    });

    test('directive parsing handles multi-line show clauses', () {
      final directives = directivesOf(
        "import 'package:a/a.dart'\n    show A;\nexport \"b.dart\" show B;",
      );
      expect(directives.map((d) => d.uri), ['package:a/a.dart', 'b.dart']);
      expect(directives.last.isRelative, isTrue);
    });
  });
}
