targets:
  $default:
    builders:
      drift_dev:
        options:
          store_date_time_values_as_text: false
          sql:
            dialect: sqlite
            options:
              version: "3.45"
      json_serializable:
        options:
          field_rename: snake
          explicit_to_json: true
