import 'package:flutter/widgets.dart';
import 'package:material_symbols_icons/symbols.dart';

/// The icons users can pick for categories and accounts, stored by key.
/// Material Symbols Rounded (DESIGN §10); const so unused glyphs tree-shake.
abstract final class CategoryIcons {
  static const fallback = Symbols.category_rounded;

  static const Map<String, IconData> all = {
    'restaurant': Symbols.restaurant_rounded,
    'local_cafe': Symbols.local_cafe_rounded,
    'fastfood': Symbols.fastfood_rounded,
    'lunch_dining': Symbols.lunch_dining_rounded,
    'bakery_dining': Symbols.bakery_dining_rounded,
    'icecream': Symbols.icecream_rounded,
    'local_bar': Symbols.local_bar_rounded,
    'shopping_basket': Symbols.shopping_basket_rounded,
    'shopping_bag': Symbols.shopping_bag_rounded,
    'store': Symbols.store_rounded,
    'checkroom': Symbols.checkroom_rounded,
    'directions_bus': Symbols.directions_bus_rounded,
    'train': Symbols.train_rounded,
    'local_taxi': Symbols.local_taxi_rounded,
    'two_wheeler': Symbols.two_wheeler_rounded,
    'directions_car': Symbols.directions_car_rounded,
    'local_gas_station': Symbols.local_gas_station_rounded,
    'local_parking': Symbols.local_parking_rounded,
    'flight': Symbols.flight_rounded,
    'hotel': Symbols.hotel_rounded,
    'beach_access': Symbols.beach_access_rounded,
    'home': Symbols.home_rounded,
    'apartment': Symbols.apartment_rounded,
    'chair': Symbols.chair_rounded,
    'build': Symbols.build_rounded,
    'cleaning_services': Symbols.cleaning_services_rounded,
    'local_laundry_service': Symbols.local_laundry_service_rounded,
    'receipt_long': Symbols.receipt_long_rounded,
    'bolt': Symbols.bolt_rounded,
    'water_drop': Symbols.water_drop_rounded,
    'wifi': Symbols.wifi_rounded,
    'phone_iphone': Symbols.phone_iphone_rounded,
    'subscriptions': Symbols.subscriptions_rounded,
    'favorite': Symbols.favorite_rounded,
    'local_hospital': Symbols.local_hospital_rounded,
    'medication': Symbols.medication_rounded,
    'fitness_center': Symbols.fitness_center_rounded,
    'spa': Symbols.spa_rounded,
    'content_cut': Symbols.content_cut_rounded,
    'movie': Symbols.movie_rounded,
    'music_note': Symbols.music_note_rounded,
    'sports_esports': Symbols.sports_esports_rounded,
    'sports_soccer': Symbols.sports_soccer_rounded,
    'school': Symbols.school_rounded,
    'book': Symbols.book_rounded,
    'child_care': Symbols.child_care_rounded,
    'pets': Symbols.pets_rounded,
    'celebration': Symbols.celebration_rounded,
    'card_giftcard': Symbols.card_giftcard_rounded,
    'redeem': Symbols.redeem_rounded,
    'volunteer_activism': Symbols.volunteer_activism_rounded,
    'mosque': Symbols.mosque_rounded,
    'church': Symbols.church_rounded,
    'smoking_rooms': Symbols.smoking_rooms_rounded,
    'work': Symbols.work_rounded,
    'laptop_mac': Symbols.laptop_mac_rounded,
    'payments': Symbols.payments_rounded,
    'attach_money': Symbols.attach_money_rounded,
    'savings': Symbols.savings_rounded,
    'account_balance': Symbols.account_balance_rounded,
    'account_balance_wallet': Symbols.account_balance_wallet_rounded,
    'trending_up': Symbols.trending_up_rounded,
    'currency_exchange': Symbols.currency_exchange_rounded,
    'sell': Symbols.sell_rounded,
    'storefront': Symbols.storefront_rounded,
    'more_horiz': Symbols.more_horiz_rounded,
  };

  static IconData of(String key) => all[key] ?? fallback;
}
